### ISSUE TITLE
Distorted sound

### ISSUE THREAD

**Issue by katananja** [vgmrips/vgmplay#51]
Listening to Track 8 - Germany (Stage 4) of this playlist:
https://vgmrips.net/packs/pack/city-connection-arcade

It sound distorted. Compiling the code and using ``./vgm2wav --loop-count 1 "08 Germany (Stage 4).vgz" citycon.wav`` the waveform looks strange.
![tracks000](https://user-images.githubusercontent.com/9029191/52102178-371e5d80-25c6-11e9-9f16-5c787b7b8770.png)

The dc-offset of that track also looks off.
For reference I've attached a direct sample from a YM2203 hardware from project [RE:birth](http://ym2203.com/rebirth/?p=62)
[hw.zip](https://github.com/vgmrips/vgmplay/files/2820083/hw.zip)

**Comment by superctr** [comment]
It is because the SSG (AY-3-8910 part, it is output directly by the FM chip instead of going through the DAC) only outputs a positive voltage and that is simulated here. The real hardware probably filters the SSG output.

vgmplay does not emulate any filtering done outside the sound chips themselves (with few special cases), so I don't think this particular behavior will be changed.

**Comment by ValleyBell** [comment]
... ohh, I think I know what it is.

The song uses the "OPN prescaler" stuff and then uses an instrument that only sounds right when the FM chip is emulated at the correct sample rate.  
Unfortunately VGMPlay currently doesn't support sample rate changes for FM chips.  
But I'll try to make a fix in libvgm.

**Comment by ValleyBell** [comment]
This should be fixed with ValleyBell/libvgm@ee17446493124a3d610f25a736b3436aedf71c0b  
It was on my TODO list anyway.

Here is an MP3 of the song playing using the just-fixed libvgm:
[CityConnection_Germany_(fixed).zip](https://github.com/vgmrips/vgmplay/files/2824374/CityConnection_Germany_.fixed.zip)

**Comment by katananja** [comment]
Hello @ValleyBell congratulations to you too on the QSound Engine, oh my God! The whole gang is here!
Thank you for the fix man, that is the correct tune!

I'm finishing up a few things here, I'll decode that Chun-Li soundtrack for you guys.

**THANK YOU!**

**Comment by superctr** [comment]
I think you should give credit to Vas Crabb from the MAME team for emulating the DSP in the first place. We just took the DSP code and ported it to C.

Yes I am aware of how the qsound effect works, technically it's not quite that complicated. And the secrets about how the filter was designed are in the (now-expired) patents that are mentioned in the Qsound splash screen anyway...

If you want another example of a track that you really only can hear with the effect enabled, it would be the bass track in "[Irene](https://vgmrips.net/packs/pack/street-fighter-ex2-plus-zn-2#18-irene-goddess-of-freedom-stage)" from Street Fighter EX2 Plus. It is almost inaudible with the old emulator (that you hear on the vgmrips website).

**Comment by katananja** [comment]
Vas Crabb has issues with me, issues I don't know what and personally I really don't care about. You guys got the job done!

About the patents... they are not complete, what you see in there doesn't complete the circle, it did expired but I still have a non-disclosure contract signed.

For convenience and easy reference I've done both, decoded and non-decoded, the non-decoded is just the vgmplay log. It will be possible to hear the "bongos" (ta-da-da/ta-da-da) we use to do hardware testing, that is the missing part in that patent.

[decoded.zip](https://github.com/vgmrips/vgmplay/files/2824560/decoded.zip)
[non-decoded.zip](https://github.com/vgmrips/vgmplay/files/2824561/non-decoded.zip)

Hope you like it!
Thank you @superctr and @ValleyBell!
You guys are **THE BEST!**

**Comment by katananja** [comment]
I was listening to your fix @ValleyBell with headphones, there is still a ringing type noise inside the tone.

Don't know if this might help you improve your sound engine or not, I'm not a software developer, fmgen 008 is a open source FM Sound Generator, rumor says that this guys are the engineers that created the YM2203 and other sound engines.
http://retropc.net/cisc/m88/download.html

All the files are SHIFT_JIS encoded, the code is free to use, the autor only asks to drop him a line if you use it in you project.

Thank you again @ValleyBell !

**Comment by superctr** [comment]
Fmgen is quite old and based on ancient MAME sources, as you can tell from the source code. I think considering that, it would probably fall under the "no commercial use" MAME license as well.

**Comment by katananja** [comment]
Thank you @superctr
